services:
  app:
    image: ${IMAGE_TAG:-ghcr.io/scottrbk/auth:latest}
    build: 
      context: ${BUILD_CONTEXT:-..}
    ports:
      - "${PORT:-8010}:${CONTAINER_PORT:-8010}"
    env_file:
      - .env.test
    container_name: ${CONTAINER_NAME:-app}

  tests:
    build: ..
    depends_on:
      - app
    environment:
      - APP_NAME=app
      - APP_PORT=8010
    command: uv run pytest -m integration -v



