name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run unit tests
        run: uv run pytest tests/unit -v --tb=short

      - name: Run integration tests
        run: uv run pytest tests/integration -v --tb=short
        env:
          APP_URL: http://localhost:8020

      - name: Cleanup
        if: always()
        run: echo "Tests completed"
