name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs: 
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        id: repo
        run: echo "name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull built image
        run: docker pull ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:latest

      - name: Run integration tests
        run: docker compose -f docker/docker-compose.test.yml up --exit-code-from tests
        env:
          IMAGE_TAG: ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:latest
        
      - name: Clean up
        if: always()
        run: docker compose -f docker/docker-compose.test.yml down
